//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCI.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sci_bdEntities : DbContext
    {
        public sci_bdEntities()
            : base("name=sci_bdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<entrada> entrada { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<producto_has_proveedor> producto_has_proveedor { get; set; }
        public virtual DbSet<proveedor> proveedor { get; set; }
        public virtual DbSet<salida> salida { get; set; }
        public virtual DbSet<ubicacion> ubicacion { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
